import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { describe, expect, it } from 'vitest';

/*
 * Self-hosted font asset audit.
 *
 * v0.2 promised in CHANGELOG / UI_GUIDE / TOKENS that web fonts ship from
 * `apps/blog/public/fonts/` and never via CDN. v0.5 collapses the v0.2
 * editorial-technical triad to a single self-hosted Korean+Latin family
 * (Noto Sans KR), with code blocks falling through to the system monospace
 * stack — no mono webfont ships. This test is the structural enforcement
 * of both promises: tokens.css advertising "Noto Sans KR" while the woff2
 * files are missing would silently degrade everyone to system fallbacks.
 *
 * Lives under `apps/blog/tests` because the assets live in apps/blog/public —
 * the assertion is per-app even though the @font-face rules are in
 * theme-default. Runs at unit-test speed; no build required.
 */

const FONTS_DIR = path.resolve(__dirname, '..', 'public', 'fonts');
const LICENSES_DIR = path.join(FONTS_DIR, 'LICENSES');

const REQUIRED_FONT_FILES = [
  // Generated by `scripts/vendor-fonts.mjs` from the bundled
  // `Noto_Sans_KR.zip`. The prebuild hook runs the script automatically; the
  // zip is committed so the build is reproducible without external downloads.
  'NotoSansKR-Regular.woff2',
  'NotoSansKR-Bold.woff2',
] as const;

const REQUIRED_LICENSE_FILES = [
  // Copied verbatim from the upstream Noto Sans KR distribution by
  // `scripts/vendor-fonts.mjs`.
  'NotoSansKR-OFL.txt',
] as const;

describe('public/fonts/ — self-hosted Noto Sans KR assets', () => {
  for (const file of REQUIRED_FONT_FILES) {
    it(`ships ${file} (non-empty)`, async () => {
      const stat = await fs.stat(path.join(FONTS_DIR, file));
      expect(stat.isFile()).toBe(true);
      // woff2 minimum sane size — anything under 1 KB is almost certainly a
      // truncated download or LFS pointer.
      expect(stat.size).toBeGreaterThan(1024);
    });
  }

  for (const file of REQUIRED_LICENSE_FILES) {
    it(`ships license/notice ${file}`, async () => {
      const stat = await fs.stat(path.join(LICENSES_DIR, file));
      expect(stat.isFile()).toBe(true);
      expect(stat.size).toBeGreaterThan(0);
    });
  }
});
